environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"

build_script:
  - python setup.py install

test_script:
  - mididump.py mary.mid
  - nosetests --with-coverage --cover-package=midi
